// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MoviesIndexController from "./movies_index_controller"
application.register("movies-index", MoviesIndexController)

import UpdateCardController from "./update_card_controller"
application.register("update-card", UpdateCardController)
